name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19

    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: true

    - name: Build and Deploy React app to GitHub Pages
      run: |
        pnpm i
        pnpm run build
        git config user.name github-actions
        git config user.email github-actions@github.com
        git --work-tree build add --all
        git commit -m "Automatic Build and Deploy run by GitHub Actions"
        git push origin HEAD:gh-pages --force